displayName=Death Shamer Improved
author=Myles
support=https://github.com/MylesAdams/deathshamerimproved
description=Takes a screenshot of deaths. Supports discord webhook integration.
tags=death, raid, raids, shame, tob, theater, cox, chambers, discord, webhook
plugins=mylesadams.deathshamerimproved.DeathShamerImprovedPlugin
